[package]
name = "vicsek"
version = "0.1.0"
authors = ["Hendrik Schawe <surt91gmail.com>"]

[dependencies]
rand = "*"
clap = "*"
rayon = "*"

piston = "*"
pistoncore-glutin_window = "*"
pistoncore-sdl2_window = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"

fps_counter = "*"
